services:
  - type: web
    name: grow-a-garden-stock-tracker
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-*/chrome-linux64/chrome
